# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 16 Sep 2021 11:44:45 +0000
*               @ALL          0
*               @user         8
