# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 16 Sep 2021 11:44:45 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

dhkim:$2y$10$1OJ5RQ0RIp6ik0puV712yunqXaqFCqbBtFqDf/AYLU9A43YQPibhG:dhkim:daitchkim@outlook.com:admin,user
